import { createContext, useContext, useMemo, useState, type ReactNode } from 'react'

export type Language = 'pt' | 'en' | 'es'

const LANGUAGE_KEY = 'planejamento-motorista-language'

type Dictionary = Record<string, string>

const dictionaries: Record<Language, Dictionary> = {
  pt: {
    appName: 'Planejamento Motorista',
    appShort: 'Planejamento',
    driver: 'Motorista',
    dashboard: 'Dashboard',
    home: 'Início',
    goals: 'Metas',
    earnings: 'Ganhos',
    receipts: 'Recebimentos',
    expenses: 'Gastos',
    fixedExpenses: 'Despesas Fixas',
    week: 'Semana',
    month: 'Mês',
    maintenance: 'Manutenções',
    history: 'Histórico',
    save: 'Salvar',
    saving: 'Salvando...',
    edit: 'Editar',
    delete: 'Excluir',
    details: 'Detalhes',
    hide: 'Ocultar',
    cancel: 'Cancelar',
    logout: 'Sair',
    light: 'Claro',
    dark: 'Escuro',
    language: 'Idioma',
    openMenu: 'Abrir menu',
    closeMenu: 'Fechar menu',
    toggleTheme: 'Alternar tema',
    login: 'Entrar',
    signup: 'Criar conta',
    email: 'E-mail',
    password: 'Senha',
    emailPlaceholder: 'voce@email.com',
    passwordPlaceholder: 'Mínimo 6 caracteres',
    loginTitle: 'Entre para controlar sua rotina',
    loginSubtitle: 'Ganhos, gastos, metas e histórico em uma tela simples para o dia a dia.',
    loginSubmit: 'Entrar no app',
    signupSubmit: 'Criar minha conta',
    wait: 'Aguarde...',
    forgotPassword: 'Esqueci minha senha',
    resetSent: 'Enviamos um link para redefinir sua senha.',
    signupSent: 'Conta criada! Verifique seu e-mail para confirmar o cadastro antes de entrar.',
    unexpectedError: 'Erro inesperado. Tente novamente.',
    setupRequired: 'Configuração necessária',
    setupText: 'Crie um projeto gratuito no Supabase, rode o arquivo supabase/schema.sql no SQL Editor e preencha o arquivo .env com as credenciais do projeto.',
    protectedData: 'Dados protegidos',
    quickAccess: 'Entrada rápida',
    showPassword: 'Mostrar senha',
    hidePassword: 'Ocultar senha',
    today: 'Hoje',
    currentWeek: 'Semana atual',
    currentMonth: 'Mês atual',
    previousWeek: 'Semana anterior',
    nextWeek: 'Próxima semana',
    previousMonth: 'Mês anterior',
    nextMonth: 'Próximo mês',
    earned: 'atingidos',
    setGoalInGoals: 'Defina uma meta na aba Metas',
    earningsByPlatform: 'Ganhos por plataforma',
    monthExpensesByCategory: 'Gastos do mês por categoria',
    total: 'Total',
    balance: 'Saldo',
    dailyAverage: 'Média por dia',
    workedDays: 'Dias trabalhados',
    perHour: 'Por hora',
    platform: 'Aplicativo',
    registerEarning: 'Registrar ganho',
    registerExpense: 'Registrar gasto',
    registerMaintenance: 'Registrar manutenção',
    noRecords: 'Nada registrado nesse período.',
    typePlatformValues: 'Digite o valor de cada aplicativo e salve.',
    launchReceipts: 'Lançar recebimentos',
    quickSaveToday: 'Use para salvar rápido o que entrou hoje.',
    day: 'Dia',
    kmToday: 'Km rodados hoje',
    workedHours: 'Horas trabalhadas',
    totalReceived: 'Total recebido',
    rides: 'Corridas',
    drivenKm: 'Km rodados',
    hours: 'Horas',
    viewBy: 'Ver ganhos por',
    backToToday: 'Voltar para hoje',
    chooseMonth: 'Escolha o mês',
    chooseWeekDay: 'Escolha um dia da semana',
    showPlatform: 'Mostrar plataforma',
    allPlatforms: 'Todas as plataformas',
    allMonths: 'Todos os meses',
    noEarningsPeriod: 'Nenhum ganho registrado neste período.',
    tapToAddFirstEarning: 'Toque no botão abaixo para adicionar o primeiro valor recebido.',
    fillEarningHelp: 'Preencha o valor recebido. Os outros campos ajudam nos relatórios, mas podem ficar em branco.',
    receivedValue: 'Valor recebido (R$)',
    earningDay: 'Dia do ganho',
    usedPlatform: 'Plataforma usada',
    howManyRides: 'Quantas corridas?',
    observation: 'Observação',
    optional: 'Opcional',
    saveEarning: 'Salvar ganho',
    editEarning: 'Editar ganho',
    deleteEarning: 'Excluir ganho',
    expenseSubtitle: 'Registre as despesas do dia a dia.',
    totalGeneral: 'Total geral',
    totalMonth: 'Total do mês',
    includesFixedExpenses: 'Inclui {value} de despesas fixas.',
    period: 'Período',
    filterMonth: 'Filtrar mês',
    everything: 'Tudo',
    category: 'Categoria',
    all: 'Todas',
    noExpensesPeriod: 'Nenhum gasto registrado neste período.',
    view: 'Ver',
    newExpense: 'Novo gasto',
    editExpense: 'Editar gasto',
    deleteExpense: 'Excluir gasto',
    date: 'Data',
    expenseName: 'Nome do gasto',
    description: 'Descrição',
    receiptOptional: 'Comprovante (opcional)',
    receipt: 'Comprovante',
    historySubtitle: 'Resumo de ganhos e gastos, atualizado automaticamente',
    refreshing: 'Atualizando...',
    refresh: 'Atualizar',
    newEntry: 'Nova entrada',
    monthly: 'Mensal',
    annual: 'Anual',
    totalPeriod: 'Total do período',
    noEarningsHistory: 'Nenhum mês no histórico de ganhos.',
    noExpensesHistory: 'Nenhum mês no histórico de gastos.',
    monthsSavedAutomatically: 'Os meses são salvos automaticamente.',
    editEntry: 'Editar entrada',
    deleteEntry: 'Excluir entrada',
    maintenanceSubtitle: 'Pneus, óleo, bateria, limpeza e revisões.',
    periodTotal: 'Total do período',
    type: 'Tipo',
    allPlural: 'Todos',
    yearHistory: 'Histórico do ano',
    noMaintenanceYear: 'Nenhuma manutenção registrada em {year}.',
    totalInYear: 'Total em {year}:',
    moreThisMonth: 'mais neste mês',
    editMaintenance: 'Editar manutenção',
    newMaintenance: 'Nova manutenção',
    deleteMaintenance: 'Excluir manutenção',
    writeMaintenanceType: 'Escreva o tipo de manutenção',
    carTotalKm: 'Km total do carro',
    dayKm: 'Km do dia',
    monthKm: 'Km do mês',
    paidInInstallments: 'Foi parcelado',
    installmentsCount: 'Em quantas vezes',
    cash: 'À vista',
    goalsSubtitle: 'Defina suas metas de ganho diária, semanal e mensal',
    currentPeriodEarnings: 'ganhos no período atual',
    goalReached: 'Meta atingida! Parabéns!',
    missingGoalValue: 'Informe um valor maior que zero.',
    goalValue: 'Valor da meta (R$)',
    noGoal: 'Sem meta',
    fixedExpenseSubtitle: 'Cadastre gastos que se repetem e o app soma automaticamente nos totais.',
    newFixedExpense: 'Nova despesa fixa',
    registerFixedExpense: 'Cadastrar despesa fixa',
    noFixedExpense: 'Nenhuma despesa fixa cadastrada.',
    editFixedExpense: 'Editar despesa fixa',
    deleteFixedExpense: 'Excluir despesa fixa',
    repeat: 'Repetição',
    repeatHint: '"Por dia" soma o valor a cada dia do período; "Por semana" a cada semana; "Por mês" a cada mês.',
    activeIncludeTotals: 'Ativa (incluir nos totais)',
    activate: 'Ativar',
    deactivate: 'Desativar',
    active: 'Ativa',
    paused: 'Pausada',
    loading: 'Carregando...',
    todayResult: 'Resultado de hoje',
    received: 'Recebido',
    spent: 'Gasto',
    earningsReceived: 'ganhos recebidos',
    kmDriven: 'km rodados',
    monthSummary: 'Resumo do mês',
    year: 'Ano',
    noGoalSet: 'Sem meta definida',
    goalPercent: 'da meta',
    last7Days: 'Últimos 7 dias',
    noExpensesThisMonth: 'Nenhum gasto registrado este mês.',
    monthResult: 'Resultado do mês',
    earningsMinusExpenses: 'ganhos - gastos',
    dailyGoal: 'Meta diária',
    weeklyGoal: 'Meta semanal',
    monthlyGoal: 'Meta mensal',
    weekRange: 'Semana de',
    to: 'a',
    weekBalance: 'Saldo da semana',
    monthBalance: 'Saldo do mês',
    of7Days: 'de 7 dias',
    daysWithEarnings: 'dias com ganho',
    hourlyEarning: 'Ganho por hora',
    reportedHours: 'h informadas',
    daysInMonth: 'dias no mês',
    entries: 'Lançamentos',
    registeredEarnings: 'ganhos registrados',
    result: 'Resultado',
    positive: 'Positivo',
    negative: 'Negativo',
  },
  en: {
    appName: 'Driver Planner',
    appShort: 'Planner',
    driver: 'Driver',
    dashboard: 'Dashboard',
    home: 'Home',
    goals: 'Goals',
    earnings: 'Earnings',
    receipts: 'Receipts',
    expenses: 'Expenses',
    fixedExpenses: 'Fixed Expenses',
    week: 'Week',
    month: 'Month',
    maintenance: 'Maintenance',
    history: 'History',
    save: 'Save',
    saving: 'Saving...',
    edit: 'Edit',
    delete: 'Delete',
    details: 'Details',
    hide: 'Hide',
    cancel: 'Cancel',
    logout: 'Log out',
    light: 'Light',
    dark: 'Dark',
    language: 'Language',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    toggleTheme: 'Toggle theme',
    login: 'Sign in',
    signup: 'Create account',
    email: 'Email',
    password: 'Password',
    emailPlaceholder: 'you@email.com',
    passwordPlaceholder: 'At least 6 characters',
    loginTitle: 'Sign in to manage your routine',
    loginSubtitle: 'Earnings, expenses, goals and history in a simple daily view.',
    loginSubmit: 'Enter app',
    signupSubmit: 'Create my account',
    wait: 'Please wait...',
    forgotPassword: 'Forgot password',
    resetSent: 'We sent a link to reset your password.',
    signupSent: 'Account created! Check your email before signing in.',
    unexpectedError: 'Unexpected error. Try again.',
    setupRequired: 'Setup required',
    setupText: 'Create a free Supabase project, run supabase/schema.sql in the SQL Editor and fill the .env file with your project credentials.',
    protectedData: 'Protected data',
    quickAccess: 'Quick access',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    today: 'Today',
    currentWeek: 'Current week',
    currentMonth: 'Current month',
    previousWeek: 'Previous week',
    nextWeek: 'Next week',
    previousMonth: 'Previous month',
    nextMonth: 'Next month',
    earned: 'reached',
    setGoalInGoals: 'Set a goal in the Goals tab',
    earningsByPlatform: 'Earnings by platform',
    monthExpensesByCategory: 'Monthly expenses by category',
    total: 'Total',
    balance: 'Balance',
    dailyAverage: 'Daily average',
    workedDays: 'Worked days',
    perHour: 'Per hour',
    platform: 'Platform',
    registerEarning: 'Register earning',
    registerExpense: 'Register expense',
    registerMaintenance: 'Register maintenance',
    noRecords: 'No records in this period.',
    typePlatformValues: 'Type the value for each app and save.',
    launchReceipts: 'Add receipts',
    quickSaveToday: 'Use this to quickly save what came in today.',
    day: 'Day',
    kmToday: 'Km driven today',
    workedHours: 'Worked hours',
    totalReceived: 'Total received',
    rides: 'Rides',
    drivenKm: 'Km driven',
    hours: 'Hours',
    viewBy: 'View earnings by',
    backToToday: 'Back to today',
    chooseMonth: 'Choose month',
    chooseWeekDay: 'Choose a day of the week',
    showPlatform: 'Show platform',
    allPlatforms: 'All platforms',
    allMonths: 'All months',
    noEarningsPeriod: 'No earnings registered in this period.',
    tapToAddFirstEarning: 'Tap the button below to add the first received value.',
    fillEarningHelp: 'Fill in the received value. The other fields help with reports, but can stay blank.',
    receivedValue: 'Received value (R$)',
    earningDay: 'Earning day',
    usedPlatform: 'Used platform',
    howManyRides: 'How many rides?',
    observation: 'Note',
    optional: 'Optional',
    saveEarning: 'Save earning',
    editEarning: 'Edit earning',
    deleteEarning: 'Delete earning',
    expenseSubtitle: 'Register daily expenses.',
    totalGeneral: 'Overall total',
    totalMonth: 'Month total',
    includesFixedExpenses: 'Includes {value} in fixed expenses.',
    period: 'Period',
    filterMonth: 'Filter month',
    everything: 'All',
    category: 'Category',
    all: 'All',
    noExpensesPeriod: 'No expenses registered in this period.',
    view: 'View',
    newExpense: 'New expense',
    editExpense: 'Edit expense',
    deleteExpense: 'Delete expense',
    date: 'Date',
    expenseName: 'Expense name',
    description: 'Description',
    receiptOptional: 'Receipt (optional)',
    receipt: 'Receipt',
    historySubtitle: 'Summary of earnings and expenses, updated automatically',
    refreshing: 'Updating...',
    refresh: 'Update',
    newEntry: 'New entry',
    monthly: 'Monthly',
    annual: 'Annual',
    totalPeriod: 'Period total',
    noEarningsHistory: 'No month in earnings history.',
    noExpensesHistory: 'No month in expense history.',
    monthsSavedAutomatically: 'Months are saved automatically.',
    editEntry: 'Edit entry',
    deleteEntry: 'Delete entry',
    maintenanceSubtitle: 'Tires, oil, battery, cleaning and checkups.',
    periodTotal: 'Period total',
    type: 'Type',
    allPlural: 'All',
    yearHistory: 'Year history',
    noMaintenanceYear: 'No maintenance registered in {year}.',
    totalInYear: 'Total in {year}:',
    moreThisMonth: 'more this month',
    editMaintenance: 'Edit maintenance',
    newMaintenance: 'New maintenance',
    deleteMaintenance: 'Delete maintenance',
    writeMaintenanceType: 'Write the maintenance type',
    carTotalKm: 'Car total km',
    dayKm: 'Day km',
    monthKm: 'Month km',
    paidInInstallments: 'Paid in installments',
    installmentsCount: 'Number of installments',
    cash: 'Cash',
    goalsSubtitle: 'Set your daily, weekly and monthly earning goals',
    currentPeriodEarnings: 'earnings in the current period',
    goalReached: 'Goal reached! Congratulations!',
    missingGoalValue: 'Enter a value greater than zero.',
    goalValue: 'Goal value (R$)',
    noGoal: 'No goal',
    fixedExpenseSubtitle: 'Register recurring expenses and the app automatically adds them to totals.',
    newFixedExpense: 'New fixed expense',
    registerFixedExpense: 'Register fixed expense',
    noFixedExpense: 'No fixed expense registered.',
    editFixedExpense: 'Edit fixed expense',
    deleteFixedExpense: 'Delete fixed expense',
    repeat: 'Repeat',
    repeatHint: '"Daily" adds the value for each day in the period; "Weekly" for each week; "Monthly" for each month.',
    activeIncludeTotals: 'Active (include in totals)',
    activate: 'Activate',
    deactivate: 'Deactivate',
    active: 'Active',
    paused: 'Paused',
    loading: 'Loading...',
    todayResult: 'Today result',
    received: 'Received',
    spent: 'Spent',
    earningsReceived: 'earnings received',
    kmDriven: 'km driven',
    monthSummary: 'Month summary',
    year: 'Year',
    noGoalSet: 'No goal set',
    goalPercent: 'of goal',
    last7Days: 'Last 7 days',
    noExpensesThisMonth: 'No expenses registered this month.',
    monthResult: 'Month result',
    earningsMinusExpenses: 'earnings - expenses',
    dailyGoal: 'Daily goal',
    weeklyGoal: 'Weekly goal',
    monthlyGoal: 'Monthly goal',
    weekRange: 'Week from',
    to: 'to',
    weekBalance: 'Week balance',
    monthBalance: 'Month balance',
    of7Days: 'of 7 days',
    daysWithEarnings: 'days with earnings',
    hourlyEarning: 'Hourly earning',
    reportedHours: 'h reported',
    daysInMonth: 'days in month',
    entries: 'Entries',
    registeredEarnings: 'registered earnings',
    result: 'Result',
    positive: 'Positive',
    negative: 'Negative',
  },
  es: {
    appName: 'Planificador Motorista',
    appShort: 'Planificador',
    driver: 'Motorista',
    dashboard: 'Panel',
    home: 'Inicio',
    goals: 'Metas',
    earnings: 'Ganancias',
    receipts: 'Recibos',
    expenses: 'Gastos',
    fixedExpenses: 'Gastos Fijos',
    week: 'Semana',
    month: 'Mes',
    maintenance: 'Mantenimientos',
    history: 'Historial',
    save: 'Guardar',
    saving: 'Guardando...',
    edit: 'Editar',
    delete: 'Eliminar',
    details: 'Detalles',
    hide: 'Ocultar',
    cancel: 'Cancelar',
    logout: 'Salir',
    light: 'Claro',
    dark: 'Oscuro',
    language: 'Idioma',
    openMenu: 'Abrir menú',
    closeMenu: 'Cerrar menú',
    toggleTheme: 'Cambiar tema',
    login: 'Entrar',
    signup: 'Crear cuenta',
    email: 'Correo',
    password: 'Contraseña',
    emailPlaceholder: 'tu@email.com',
    passwordPlaceholder: 'Mínimo 6 caracteres',
    loginTitle: 'Entra para controlar tu rutina',
    loginSubtitle: 'Ganancias, gastos, metas e historial en una vista diaria simple.',
    loginSubmit: 'Entrar a la app',
    signupSubmit: 'Crear mi cuenta',
    wait: 'Espera...',
    forgotPassword: 'Olvidé mi contraseña',
    resetSent: 'Enviamos un enlace para restablecer tu contraseña.',
    signupSent: 'Cuenta creada. Revisa tu correo antes de entrar.',
    unexpectedError: 'Error inesperado. Inténtalo de nuevo.',
    setupRequired: 'Configuración necesaria',
    setupText: 'Crea un proyecto gratuito en Supabase, ejecuta supabase/schema.sql en SQL Editor y completa el archivo .env con las credenciales.',
    protectedData: 'Datos protegidos',
    quickAccess: 'Acceso rápido',
    showPassword: 'Mostrar contraseña',
    hidePassword: 'Ocultar contraseña',
    today: 'Hoy',
    currentWeek: 'Semana actual',
    currentMonth: 'Mes actual',
    previousWeek: 'Semana anterior',
    nextWeek: 'Próxima semana',
    previousMonth: 'Mes anterior',
    nextMonth: 'Próximo mes',
    earned: 'alcanzados',
    setGoalInGoals: 'Define una meta en la pestaña Metas',
    earningsByPlatform: 'Ganancias por plataforma',
    monthExpensesByCategory: 'Gastos del mes por categoría',
    total: 'Total',
    balance: 'Saldo',
    dailyAverage: 'Promedio diario',
    workedDays: 'Días trabajados',
    perHour: 'Por hora',
    platform: 'Aplicación',
    registerEarning: 'Registrar ganancia',
    registerExpense: 'Registrar gasto',
    registerMaintenance: 'Registrar mantenimiento',
    noRecords: 'No hay registros en este período.',
    typePlatformValues: 'Escribe el valor de cada app y guarda.',
    launchReceipts: 'Registrar recibos',
    quickSaveToday: 'Úsalo para guardar rápido lo que entró hoy.',
    day: 'Día',
    kmToday: 'Km recorridos hoy',
    workedHours: 'Horas trabajadas',
    totalReceived: 'Total recibido',
    rides: 'Carreras',
    drivenKm: 'Km recorridos',
    hours: 'Horas',
    viewBy: 'Ver ganancias por',
    backToToday: 'Volver a hoy',
    chooseMonth: 'Elige el mes',
    chooseWeekDay: 'Elige un día de la semana',
    showPlatform: 'Mostrar plataforma',
    allPlatforms: 'Todas las plataformas',
    allMonths: 'Todos los meses',
    noEarningsPeriod: 'Ninguna ganancia registrada en este período.',
    tapToAddFirstEarning: 'Toca el botón de abajo para agregar el primer valor recibido.',
    fillEarningHelp: 'Completa el valor recibido. Los otros campos ayudan en los informes, pero pueden quedar vacíos.',
    receivedValue: 'Valor recibido (R$)',
    earningDay: 'Día de la ganancia',
    usedPlatform: 'Plataforma usada',
    howManyRides: '¿Cuántas carreras?',
    observation: 'Observación',
    optional: 'Opcional',
    saveEarning: 'Guardar ganancia',
    editEarning: 'Editar ganancia',
    deleteEarning: 'Eliminar ganancia',
    expenseSubtitle: 'Registra los gastos del día a día.',
    totalGeneral: 'Total general',
    totalMonth: 'Total del mes',
    includesFixedExpenses: 'Incluye {value} de gastos fijos.',
    period: 'Período',
    filterMonth: 'Filtrar mes',
    everything: 'Todo',
    category: 'Categoría',
    all: 'Todas',
    noExpensesPeriod: 'Ningún gasto registrado en este período.',
    view: 'Ver',
    newExpense: 'Nuevo gasto',
    editExpense: 'Editar gasto',
    deleteExpense: 'Eliminar gasto',
    date: 'Fecha',
    expenseName: 'Nombre del gasto',
    description: 'Descripción',
    receiptOptional: 'Comprobante (opcional)',
    receipt: 'Comprobante',
    historySubtitle: 'Resumen de ganancias y gastos, actualizado automáticamente',
    refreshing: 'Actualizando...',
    refresh: 'Actualizar',
    newEntry: 'Nuevo registro',
    monthly: 'Mensual',
    annual: 'Anual',
    totalPeriod: 'Total del período',
    noEarningsHistory: 'Ningún mes en el historial de ganancias.',
    noExpensesHistory: 'Ningún mes en el historial de gastos.',
    monthsSavedAutomatically: 'Los meses se guardan automáticamente.',
    editEntry: 'Editar registro',
    deleteEntry: 'Eliminar registro',
    maintenanceSubtitle: 'Neumáticos, aceite, batería, limpieza y revisiones.',
    periodTotal: 'Total del período',
    type: 'Tipo',
    allPlural: 'Todos',
    yearHistory: 'Historial del año',
    noMaintenanceYear: 'Ningún mantenimiento registrado en {year}.',
    totalInYear: 'Total en {year}:',
    moreThisMonth: 'más este mes',
    editMaintenance: 'Editar mantenimiento',
    newMaintenance: 'Nuevo mantenimiento',
    deleteMaintenance: 'Eliminar mantenimiento',
    writeMaintenanceType: 'Escribe el tipo de mantenimiento',
    carTotalKm: 'Km total del coche',
    dayKm: 'Km del día',
    monthKm: 'Km del mes',
    paidInInstallments: 'Fue parcelado',
    installmentsCount: 'En cuántas cuotas',
    cash: 'Al contado',
    goalsSubtitle: 'Define tus metas de ganancia diaria, semanal y mensual',
    currentPeriodEarnings: 'ganancias en el período actual',
    goalReached: '¡Meta alcanzada! ¡Felicitaciones!',
    missingGoalValue: 'Ingresa un valor mayor que cero.',
    goalValue: 'Valor de la meta (R$)',
    noGoal: 'Sin meta',
    fixedExpenseSubtitle: 'Registra gastos recurrentes y la app los suma automáticamente en los totales.',
    newFixedExpense: 'Nuevo gasto fijo',
    registerFixedExpense: 'Registrar gasto fijo',
    noFixedExpense: 'Ningún gasto fijo registrado.',
    editFixedExpense: 'Editar gasto fijo',
    deleteFixedExpense: 'Eliminar gasto fijo',
    repeat: 'Repetición',
    repeatHint: '"Por día" suma el valor cada día del período; "Por semana" cada semana; "Por mes" cada mes.',
    activeIncludeTotals: 'Activo (incluir en totales)',
    activate: 'Activar',
    deactivate: 'Desactivar',
    active: 'Activo',
    paused: 'Pausado',
    loading: 'Cargando...',
    todayResult: 'Resultado de hoy',
    received: 'Recibido',
    spent: 'Gastado',
    earningsReceived: 'ganancias recibidas',
    kmDriven: 'km recorridos',
    monthSummary: 'Resumen del mes',
    year: 'Año',
    noGoalSet: 'Sin meta definida',
    goalPercent: 'de la meta',
    last7Days: 'Últimos 7 días',
    noExpensesThisMonth: 'Ningún gasto registrado este mes.',
    monthResult: 'Resultado del mes',
    earningsMinusExpenses: 'ganancias - gastos',
    dailyGoal: 'Meta diaria',
    weeklyGoal: 'Meta semanal',
    monthlyGoal: 'Meta mensual',
    weekRange: 'Semana de',
    to: 'a',
    weekBalance: 'Saldo de la semana',
    monthBalance: 'Saldo del mes',
    of7Days: 'de 7 días',
    daysWithEarnings: 'días con ganancia',
    hourlyEarning: 'Ganancia por hora',
    reportedHours: 'h informadas',
    daysInMonth: 'días en el mes',
    entries: 'Registros',
    registeredEarnings: 'ganancias registradas',
    result: 'Resultado',
    positive: 'Positivo',
    negative: 'Negativo',
  },
}

interface LanguageContextValue {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextValue | null>(null)

function getInitialLanguage(): Language {
  try {
    const saved = localStorage.getItem(LANGUAGE_KEY)
    if (saved === 'pt' || saved === 'en' || saved === 'es') return saved
  } catch {
    // localStorage indisponível
  }
  return 'pt'
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [languageState, setLanguageState] = useState<Language>(getInitialLanguage)

  function setLanguage(language: Language) {
    setLanguageState(language)
    try {
      localStorage.setItem(LANGUAGE_KEY, language)
    } catch {
      // localStorage indisponível
    }
  }

  const value = useMemo<LanguageContextValue>(
    () => ({
      language: languageState,
      setLanguage,
      t: (key) => dictionaries[languageState][key] ?? dictionaries.pt[key] ?? key,
    }),
    [languageState],
  )

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage deve ser usado dentro de LanguageProvider')
  return context
}
